modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="loginmod"
version="1.0.0"
displayName="Login Mod"
description='''
一个简单的登录模组，要求玩家在进入服务器后使用 /login 命令登录才能移动和破坏方块。
'''
authors="COOKIE9"
displayURL="https://github.com/your-repo"

[[dependencies.loginmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.loginmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
